const questions = {
  movies: [
    { question: "Who directed 'Interstellar'?", options: ["Christopher Nolan", "James Cameron", "Denis Villeneuve", "Ridley Scott"], answer: "Christopher Nolan" },
    { question: "Which movie features the character Jack Sparrow?", options: ["Pirates of the Caribbean", "Treasure Island", "Peter Pan", "Hook"], answer: "Pirates of the Caribbean" },
    { question: "What is the name of Batman's city?", options: ["Metropolis", "Gotham", "Star City", "Central City"], answer: "Gotham" },
    { question: "Which film features dinosaurs cloned from DNA?", options: ["Jurassic Park", "King Kong", "Avatar", "Godzilla"], answer: "Jurassic Park" },
    { question: "Who played Jack in 'Titanic'?", options: ["Brad Pitt", "Leonardo DiCaprio", "Johnny Depp", "Matt Damon"], answer: "Leonardo DiCaprio" },
    { question: "Which movie is about dreams within dreams?", options: ["Inception", "Shutter Island", "Memento", "Tenet"], answer: "Inception" },
    { question: "What is the highest-grossing Marvel movie?", options: ["Avengers: Endgame", "Infinity War", "No Way Home", "Black Panther"], answer: "Avengers: Endgame" },
    { question: "Which movie features a theme park with cloned dinosaurs?", options: ["Jurassic World", "Jurassic Park", "King Kong", "Godzilla"], answer: "Jurassic Park" },
    { question: "Who directed 'Avatar'?", options: ["James Cameron", "Steven Spielberg", "George Lucas", "Peter Jackson"], answer: "James Cameron" },
    { question: "Which movie features a sinking ship?", options: ["Titanic", "Poseidon", "The Abyss", "Deepwater Horizon"], answer: "Titanic" },
    { question: "Who is the main villain in 'The Dark Knight'?", options: ["Joker", "Bane", "Two-Face", "Scarecrow"], answer: "Joker" },
    { question: "Which film is about a boxing underdog named Rocky?", options: ["Rocky", "Creed", "Raging Bull", "Million Dollar Baby"], answer: "Rocky" },
    { question: "What is the name of the wizard school in Harry Potter?", options: ["Hogwarts", "Durmstrang", "Beauxbatons", "Ilvermorny"], answer: "Hogwarts" },
    { question: "Which movie features the character Forrest Gump?", options: ["Forrest Gump", "Cast Away", "Big", "The Terminal"], answer: "Forrest Gump" },
    { question: "Who directed 'The Godfather'?", options: ["Francis Ford Coppola", "Martin Scorsese", "Steven Spielberg", "Stanley Kubrick"], answer: "Francis Ford Coppola" },
    { question: "Who directed 'Inception' (2010)?", options: ["Christopher Nolan", "Steven Spielberg", "Quentin Tarantino", "Martin Scorsese"], answer: "Christopher Nolan" },
    { question: "Which movie features the quote 'Here's looking at you, kid'?", options: ["Casablanca", "Gone with the Wind", "The Godfather", "Citizen Kane"], answer: "Casablanca" },
    { question: "What year was 'The Dark Knight' released?", options: ["2005", "2006", "2008", "2010"], answer: "2008" },
    { question: "Which film won the first Academy Award for Best Picture?", options: ["Wings", "Sunrise", "The Jazz Singer", "All Quiet on the Western Front"], answer: "Wings" },
    { question: "Who played Iron Man in the MCU?", options: ["Chris Evans", "Robert Downey Jr.", "Chris Hemsworth", "Mark Ruffalo"], answer: "Robert Downey Jr." },
    { question: "What is the highest-grossing film of all time?", options: ["Titanic", "Avengers: Endgame", "Avatar", "Star Wars: The Force Awakens"], answer: "Avatar" },
    { question: "In 'The Matrix', what color pill does Neo take?", options: ["Blue", "Green", "Red", "Yellow"], answer: "Red" },
    { question: "Who voiced Woody in 'Toy Story'?", options: ["Tim Allen", "Tom Hanks", "John Travolta", "Billy Crystal"], answer: "Tom Hanks" },
    { question: "Which director made 'Pulp Fiction'?", options: ["David Fincher", "Quentin Tarantino", "Joel Coen", "Paul Thomas Anderson"], answer: "Quentin Tarantino" },
    { question: "What is the name of the ship in 'Titanic'?", options: ["Olympic", "Britannic", "Mauretania", "Titanic"], answer: "Titanic" }
  ],
  series: [
    { question: "Who created 'Breaking Bad'?", options: ["Vince Gilligan", "David Chase", "Shonda Rhimes", "Ryan Murphy"], answer: "Vince Gilligan" },
    { question: "Which series features dragons and the Iron Throne?", options: ["Game of Thrones", "The Witcher", "Vikings", "Shadow and Bone"], answer: "Game of Thrones" },
    { question: "What is Eleven's favorite food in 'Stranger Things'?", options: ["Waffles", "Pizza", "Burgers", "Ice Cream"], answer: "Waffles" },
    { question: "Which show features Michael Scott?", options: ["The Office", "Parks and Recreation", "Brooklyn Nine-Nine", "Friends"], answer: "The Office" },
    { question: "Who plays Jon Snow?", options: ["Kit Harington", "Richard Madden", "Emilia Clarke", "Iain Glen"], answer: "Kit Harington" },
    { question: "Which series is set in Hawkins, Indiana?", options: ["Stranger Things", "Dark", "The OA", "Lost"], answer: "Stranger Things" },
    { question: "What is the name of Sheldon’s roommate in 'The Big Bang Theory'?", options: ["Leonard", "Howard", "Raj", "Stuart"], answer: "Leonard" },
    { question: "Which show features the character 'Dexter Morgan'?", options: ["Dexter", "Mindhunter", "Hannibal", "True Detective"], answer: "Dexter" },
    { question: "Which series involves a heist at the Royal Mint of Spain?", options: ["Money Heist", "Narcos", "Breaking Bad", "Ozark"], answer: "Money Heist" },
    { question: "What is the name of the bar in 'How I Met Your Mother'?", options: ["MacLaren's", "Central Perk", "The Drunken Clam", "Cheers"], answer: "MacLaren's" },
    { question: "Who is the main character in 'House of the Dragon'?", options: ["Rhaenyra Targaryen", "Daenerys", "Jon Snow", "Tyrion"], answer: "Rhaenyra Targaryen" },
    { question: "Which show features the character 'Geralt of Rivia'?", options: ["The Witcher", "Vikings", "Game of Thrones", "Shadow and Bone"], answer: "The Witcher" },
    { question: "Which platform streams 'Stranger Things'?", options: ["Netflix", "Amazon Prime", "HBO", "Disney+"], answer: "Netflix" },
    { question: "Which show features a paper company called Dunder Mifflin?", options: ["The Office", "Mad Men", "Suits", "Friends"], answer: "The Office" },
    { question: "What is the name of the prison in 'Prison Break'?", options: ["Fox River", "Alcatraz", "Shawshank", "San Quentin"], answer: "Fox River" },
    { question: "In 'Breaking Bad', what is Walter White's alias?", options: ["The Cook", "Heisenberg", "Mr. Blue", "Danger"], answer: "Heisenberg" },
    { question: "How many seasons does 'Game of Thrones' have?", options: ["6", "7", "8", "9"], answer: "8" },
    { question: "Which city is 'Friends' set in?", options: ["Los Angeles", "Chicago", "New York City", "Boston"], answer: "New York City" },
    { question: "What is the name of the coffee shop in 'Friends'?", options: ["Starbucks", "Central Perk", "The Brew", "Java House"], answer: "Central Perk" },
    { question: "Who plays Sherlock Holmes in the BBC series 'Sherlock'?", options: ["Martin Freeman", "Benedict Cumberbatch", "Tom Hiddleston", "Andrew Scott"], answer: "Benedict Cumberbatch" },
    { question: "In 'Stranger Things', what is the name of the parallel dimension?", options: ["The Shadow Realm", "The Upside Down", "The Dark Place", "The Other Side"], answer: "The Upside Down" },
    { question: "Which show features the character 'Tyrion Lannister'?", options: ["The Witcher", "Vikings", "Game of Thrones", "House of the Dragon"], answer: "Game of Thrones" },
    { question: "What streaming platform is 'The Crown' on?", options: ["HBO", "Disney+", "Amazon Prime", "Netflix"], answer: "Netflix" },
    { question: "How many episodes are in the first season of 'The Office' (US)?", options: ["4", "6", "8", "10"], answer: "6" },
    { question: "What year did 'The Sopranos' premiere?", options: ["1997", "1999", "2001", "2003"], answer: "1999" }
  ],
  games: [
    { question: "What year was 'Minecraft' officially released?", options: ["2009", "2010", "2011", "2012"], answer: "2011" },
    { question: "Which game features the character 'Master Chief'?", options: ["Call of Duty", "Halo", "Gears of War", "Destiny"], answer: "Halo" },
    { question: "What is the best-selling video game of all time?", options: ["Tetris", "Minecraft", "GTA V", "Wii Sports"], answer: "Minecraft" },
    { question: "In 'The Legend of Zelda', what is the name of the villain?", options: ["Bowser", "Ganondorf", "Ridley", "Eggman"], answer: "Ganondorf" },
    { question: "Which company makes the PlayStation?", options: ["Microsoft", "Nintendo", "Sony", "Sega"], answer: "Sony" },
    { question: "What is the name of the currency in 'Animal Crossing'?", options: ["Bells", "Coins", "Gems", "Stars"], answer: "Bells" },
    { question: "Which game introduced the 'Battle Royale' format to mainstream gaming?", options: ["Fortnite", "PUBG", "H1Z1", "Apex Legends"], answer: "PUBG" },
    { question: "What is the main character's name in 'The Last of Us'?", options: ["Nathan Drake", "Joel", "Ellie", "Tommy"], answer: "Joel" },
    { question: "In 'Among Us', what is the term for the imposters?", options: ["Killers", "Impostors", "Traitors", "Aliens"], answer: "Impostors" },
    { question: "Which game has the tagline 'The Game Has Changed'?", options: ["FIFA", "Cyberpunk 2077", "God of War", "Elden Ring"], answer: "Cyberpunk 2077" },
    { question: "Which company developed 'Minecraft'?", options: ["Mojang", "EA", "Ubisoft", "Valve"], answer: "Mojang" },
    { question: "What is the main objective in 'Fortnite' Battle Royale?", options: ["Survive", "Score points", "Build cities", "Collect coins"], answer: "Survive" },
    { question: "Which game features Kratos?", options: ["God of War", "Dark Souls", "Skyrim", "Assassin’s Creed"], answer: "God of War" },
    { question: "What is the name of Mario’s brother?", options: ["Luigi", "Wario", "Yoshi", "Toad"], answer: "Luigi" },
    { question: "Which game is set in Los Santos?", options: ["GTA V", "Watch Dogs", "Cyberpunk 2077", "Saints Row"], answer: "GTA V" },
    { question: "Which company developed 'The Witcher 3'?", options: ["CD Projekt", "Ubisoft", "Bethesda", "EA"], answer: "CD Projekt" },
    { question: "What is the name of the main character in 'God of War'?", options: ["Kratos", "Atreus", "Baldur", "Thor"], answer: "Kratos" },
    { question: "Which game features a blocky sandbox world?", options: ["Minecraft", "Roblox", "Terraria", "Fortnite"], answer: "Minecraft" },
    { question: "What is the currency in 'Fortnite'?", options: ["V-Bucks", "Coins", "Credits", "Gems"], answer: "V-Bucks" },
    { question: "Which game features the character 'Link'?", options: ["Zelda", "Mario", "Metroid", "Final Fantasy"], answer: "Zelda" },
    { question: "Which game popularized loot boxes?", options: ["Overwatch", "Fortnite", "PUBG", "Apex Legends"], answer: "Overwatch" },
    { question: "Which game is known for 'Victory Royale'?", options: ["Fortnite", "PUBG", "Apex Legends", "Warzone"], answer: "Fortnite" },
    { question: "Which game features a battle between humans and machines?", options: ["Horizon Zero Dawn", "Halo", "Gears of War", "Destiny"], answer: "Horizon Zero Dawn" },
    { question: "Which game is set in Night City?", options: ["Cyberpunk 2077", "GTA V", "Watch Dogs", "Deus Ex"], answer: "Cyberpunk 2077" },
    { question: "Which game franchise features annual soccer releases?", options: ["FIFA", "PES", "NBA 2K", "Madden"], answer: "FIFA" }
  ]
};
